### ISSUE TITLE
I am sorry to bother you, but I have been unable to solve some problems.

### ISSUE THREAD

**Issue by ztlovemst11** [bitprim/bitprim#27]
** pip install bitprim**  something is wrong ,I don't know how to find solution

Collecting bitprim
  Using cached https://files.pythonhosted.org/packages/8e/92/c7d2dfe5b94d31dc5e1ba3b48aa931a28869a47f32cc3f18d0903a08e51f/bitprim-1.1.77-py2.py3-none-any.whl
Collecting bitprim-native>=1.1.55 (from bitprim)
  Using cached https://files.pythonhosted.org/packages/79/1b/e611f20e1a7091722464fbd7e854a01271c7e886099d51d3a0738e3281d0/bitprim_native-1.1.160.tar.gz
Requirement already satisfied: conan>=1.1.1 in e:\zt_6.27\python\lib\site-packages (from bitprim) (1.6.1)
Requirement already satisfied: conan-package-tools>=0.5.4 in c:\users\planpoint\appdata\roaming\python\python35\site-packages (from bitprim) (0.18.4)
Requirement already satisfied: bottle<0.13,>=0.12.8 in e:\zt_6.27\python\lib\site-packages (from conan>=1.1.1->bitprim) (0.12.13)
Requirement already satisfied: pylint<1.9.0,>=1.8.1 in e:\zt_6.27\python\lib\site-packages (from conan>=1.1.1->bitprim) (1.8.4)
Requirement already satisfied: six>=1.10.0 in c:\users\planpoint\appdata\roaming\python\python35\site-packages (from conan>=1.1.1->bitprim) (1.11.0)
Requirement already satisfied: patch==1.16 in e:\zt_6.27\python\lib\site-packages (from conan>=1.1.1->bitprim) (1.16)
Requirement already satisfied: requests<3.0.0,>=2.7.0 in c:\users\planpoint\appdata\roaming\python\python35\site-packages (from conan>=1.1.1->bitprim) (2.11.1)
Requirement already satisfied: PyJWT<2.0.0,>=1.4.0 in e:\zt_6.27\python\lib\site-packages (from conan>=1.1.1->bitprim) (1.6.4)
Requirement already satisfied: colorama<0.4.0,>=0.3.3 in e:\zt_6.27\python\lib\site-packages (from conan>=1.1.1->bitprim) (0.3.9)
Requirement already satisfied: distro<1.2.0,>=1.0.2 in e:\zt_6.27\python\lib\site-packages (from conan>=1.1.1->bitprim) (1.1.0)
Requirement already satisfied: astroid<1.7,>=1.6 in e:\zt_6.27\python\lib\site-packages (from conan>=1.1.1->bitprim) (1.6.5)
Requirement already satisfied: PyYAML<3.13.0,>=3.11 in e:\zt_6.27\python\lib\site-packages (from conan>=1.1.1->bitprim) (3.12)
Requirement already satisfied: future==0.16.0 in c:\users\planpoint\appdata\roaming\python\python35\site-packages (from conan>=1.1.1->bitprim) (0.16.0)
Requirement already satisfied: fasteners>=0.14.1 in e:\zt_6.27\python\lib\site-packages (from conan>=1.1.1->bitprim) (0.14.1)
Requirement already satisfied: pluginbase<1.0,>=0.5 in e:\zt_6.27\python\lib\site-packages (from conan>=1.1.1->bitprim) (0.7)
Requirement already satisfied: pygments<3.0,>=2.0 in e:\zt_6.27\python\lib\site-packages (from conan>=1.1.1->bitprim) (2.2.0)
Requirement already satisfied: deprecation<2.1,>=2.0 in e:\zt_6.27\python\lib\site-packages (from conan>=1.1.1->bitprim) (2.0.5)
Requirement already satisfied: node-semver==0.2.0 in e:\zt_6.27\python\lib\site-packages (from conan>=1.1.1->bitprim) (0.2.0)
Requirement already satisfied: idna==2.6 in c:\users\planpoint\appdata\roaming\python\python35\site-packages (from conan-package-tools>=0.5.4->bitprim) (2.6)
Requirement already satisfied: tabulate==0.8.2 in c:\users\planpoint\appdata\roaming\python\python35\site-packages (from conan-package-tools>=0.5.4->bitprim) (0.8.2)
Requirement already satisfied: isort>=4.2.5 in e:\zt_6.27\python\lib\site-packages (from pylint<1.9.0,>=1.8.1->conan>=1.1.1->bitprim) (4.3.4)
Requirement already satisfied: mccabe in c:\users\planpoint\appdata\roaming\python\python35\site-packages (from pylint<1.9.0,>=1.8.1->conan>=1.1.1->bitprim) (0.6.1)
Requirement already satisfied: lazy-object-proxy in e:\zt_6.27\python\lib\site-packages (from astroid<1.7,>=1.6->conan>=1.1.1->bitprim) (1.3.1)
Requirement already satisfied: wrapt in e:\zt_6.27\python\lib\site-packages (from astroid<1.7,>=1.6->conan>=1.1.1->bitprim) (1.10.11)
Requirement already satisfied: monotonic>=0.1 in e:\zt_6.27\python\lib\site-packages (from fasteners>=0.14.1->conan>=1.1.1->bitprim) (1.5)
Requirement already satisfied: packaging in e:\zt_6.27\python\lib\site-packages (from deprecation<2.1,>=2.0->conan>=1.1.1->bitprim) (17.1)
Requirement already satisfied: pyparsing>=2.0.2 in e:\zt_6.27\python\lib\site-packages (from packaging->deprecation<2.1,>=2.0->conan>=1.1.1->bitprim) (2.2.0)
Building wheels for collected packages: bitprim-native
  Running setup.py bdist_wheel for bitprim-native ... error
  Complete output from command e:\zt_6.27\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\PLANPO~1\\AppData\\Local\\Temp\\pip-install-wqi2aa4v\\bitprim-native\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\PLANPO~1\AppData\Local\Temp\pip-wheel-uai_kzlz --python-tag cp35:
  running bdist_wheel
  running build
  --------------------------------------- BuildCommand run microarch currency
  None
  None
  *********************************************************************************************************
  C:\Users\PLANPO~1\AppData\Local\Temp\pip-install-wqi2aa4v\bitprim-native
  C:\Users\PLANPO~1\AppData\Local\Temp\pip-install-wqi2aa4v\bitprim-native
  *********************************************************************************************************
  do_conan_stuff microarch currency
  None
  Conan Remote exists, ignoring exception
  bitprim-node-cint/0.10@bitprim/stable: Not found in local cache, looking in remotes...
  bitprim-node-cint/0.10@bitprim/stable: Trying with 'conan-center'...
  bitprim-node-cint/0.10@bitprim/stable: Trying with 'bitprim'...
  ERROR: Failed requirement 'bitprim-node-cint/0.10@bitprim/stable' from 'PROJECT'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\PLANPO~1\AppData\Local\Temp\pip-install-wqi2aa4v\bitprim-native\setup.py", line 396, in <module>
      'develop': DevelopCommand,
    File "e:\zt_6.27\python\lib\site-packages\setuptools\__init__.py", line 131, in setup
      return distutils.core.setup(**attrs)
    File "e:\zt_6.27\python\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "e:\zt_6.27\python\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "e:\zt_6.27\python\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "e:\zt_6.27\python\lib\site-packages\wheel\bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "e:\zt_6.27\python\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "e:\zt_6.27\python\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\PLANPO~1\AppData\Local\Temp\pip-install-wqi2aa4v\bitprim-native\setup.py", line 252, in run
      do_build_stuff(microarch, currency)
    File "C:\Users\PLANPO~1\AppData\Local\Temp\pip-install-wqi2aa4v\bitprim-native\setup.py", line 146, in do_build_stuff
      do_conan_stuff(microarch, currency)
    File "C:\Users\PLANPO~1\AppData\Local\Temp\pip-install-wqi2aa4v\bitprim-native\setup.py", line 133, in do_conan_stuff
      c.install(refe, verify=None, manifests_interactive=None, manifests=None, options=opts)
    File "e:\zt_6.27\python\lib\site-packages\conans\client\conan_api.py", line 79, in wrapper
      return f(*args, **kwargs)
    File "e:\zt_6.27\python\lib\site-packages\conans\client\conan_api.py", line 482, in install
      no_imports=no_imports)
    File "e:\zt_6.27\python\lib\site-packages\conans\client\manager.py", line 258, in install
      profile.build_requires)
    File "e:\zt_6.27\python\lib\site-packages\conans\client\graph\graph_manager.py", line 103, in load_graph
      graph = builder.load_graph(conanfile, check_updates, update, remote_name)
    File "e:\zt_6.27\python\lib\site-packages\conans\client\graph\graph_builder.py", line 35, in load_graph
      loop_ancestors, aliased, check_updates, update, remote_name)
    File "e:\zt_6.27\python\lib\site-packages\conans\client\graph\graph_builder.py", line 96, in _load_deps
      aliased, check_updates, update, remote_name)
    File "e:\zt_6.27\python\lib\site-packages\conans\client\graph\graph_builder.py", line 214, in _create_new_node
      raise e
    File "e:\zt_6.27\python\lib\site-packages\conans\client\graph\graph_builder.py", line 209, in _create_new_node
      check_updates, update, remote_name)
    File "e:\zt_6.27\python\lib\site-packages\conans\client\graph\proxy.py", line 28, in get_recipe
      result = self._get_recipe(conan_reference, check_updates, update, remote_name)
    File "e:\zt_6.27\python\lib\site-packages\conans\client\graph\proxy.py", line 38, in _get_recipe
      ref_remote = self._download_recipe(reference, output, remote_name)
    File "e:\zt_6.27\python\lib\site-packages\conans\client\graph\proxy.py", line 134, in _download_recipe
      raise NotFoundException(msg)
  conans.errors.NotFoundException: Unable to find 'bitprim-node-cint/0.10@bitprim/stable' in remotes

  ----------------------------------------
  Failed building wheel for bitprim-native
  Running setup.py clean for bitprim-native
Failed to build bitprim-native
Installing collected packages: bitprim-native, bitprim
  Running setup.py install for bitprim-native ... error
    Complete output from command e:\zt_6.27\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\PLANPO~1\\AppData\\Local\\Temp\\pip-install-wqi2aa4v\\bitprim-native\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\PLANPO~1\AppData\Local\Temp\pip-record-h4xq9lqp\install-record.txt --single-version-externally-managed --compile:
    running install
    *********************************** InstallCommand run microarch currency
    None
    None
    *********************************************************************************************************
    C:\Users\PLANPO~1\AppData\Local\Temp\pip-install-wqi2aa4v\bitprim-native
    C:\Users\PLANPO~1\AppData\Local\Temp\pip-install-wqi2aa4v\bitprim-native
    *********************************************************************************************************
    do_conan_stuff microarch currency
    None
    Conan Remote exists, ignoring exception
    bitprim-node-cint/0.10@bitprim/stable: Not found in local cache, looking in remotes...
    bitprim-node-cint/0.10@bitprim/stable: Trying with 'conan-center'...
    bitprim-node-cint/0.10@bitprim/stable: Trying with 'bitprim'...
    ERROR: Failed requirement 'bitprim-node-cint/0.10@bitprim/stable' from 'PROJECT'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\PLANPO~1\AppData\Local\Temp\pip-install-wqi2aa4v\bitprim-native\setup.py", line 396, in <module>
        'develop': DevelopCommand,
      File "e:\zt_6.27\python\lib\site-packages\setuptools\__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
      File "e:\zt_6.27\python\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "e:\zt_6.27\python\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "e:\zt_6.27\python\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\PLANPO~1\AppData\Local\Temp\pip-install-wqi2aa4v\bitprim-native\setup.py", line 222, in run
        do_build_stuff(microarch, currency)
      File "C:\Users\PLANPO~1\AppData\Local\Temp\pip-install-wqi2aa4v\bitprim-native\setup.py", line 146, in do_build_stuff
        do_conan_stuff(microarch, currency)
      File "C:\Users\PLANPO~1\AppData\Local\Temp\pip-install-wqi2aa4v\bitprim-native\setup.py", line 133, in do_conan_stuff
        c.install(refe, verify=None, manifests_interactive=None, manifests=None, options=opts)
      File "e:\zt_6.27\python\lib\site-packages\conans\client\conan_api.py", line 79, in wrapper
        return f(*args, **kwargs)
      File "e:\zt_6.27\python\lib\site-packages\conans\client\conan_api.py", line 482, in install
        no_imports=no_imports)
      File "e:\zt_6.27\python\lib\site-packages\conans\client\manager.py", line 258, in install
        profile.build_requires)
      File "e:\zt_6.27\python\lib\site-packages\conans\client\graph\graph_manager.py", line 103, in load_graph
        graph = builder.load_graph(conanfile, check_updates, update, remote_name)
      File "e:\zt_6.27\python\lib\site-packages\conans\client\graph\graph_builder.py", line 35, in load_graph
        loop_ancestors, aliased, check_updates, update, remote_name)
      File "e:\zt_6.27\python\lib\site-packages\conans\client\graph\graph_builder.py", line 96, in _load_deps
        aliased, check_updates, update, remote_name)
      File "e:\zt_6.27\python\lib\site-packages\conans\client\graph\graph_builder.py", line 214, in _create_new_node
        raise e
      File "e:\zt_6.27\python\lib\site-packages\conans\client\graph\graph_builder.py", line 209, in _create_new_node
        check_updates, update, remote_name)
      File "e:\zt_6.27\python\lib\site-packages\conans\client\graph\proxy.py", line 28, in get_recipe
        result = self._get_recipe(conan_reference, check_updates, update, remote_name)
      File "e:\zt_6.27\python\lib\site-packages\conans\client\graph\proxy.py", line 38, in _get_recipe
        ref_remote = self._download_recipe(reference, output, remote_name)
      File "e:\zt_6.27\python\lib\site-packages\conans\client\graph\proxy.py", line 134, in _download_recipe
        raise NotFoundException(msg)
    conans.errors.NotFoundException: Unable to find 'bitprim-node-cint/0.10@bitprim/stable' in remotes

    ----------------------------------------
Command "e:\zt_6.27\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\PLANPO~1\\AppData\\Local\\Temp\\pip-install-wqi2aa4v\\bitprim-native\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\PLANPO~1\AppData\Local\Temp\pip-record-h4xq9lqp\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\PLANPO~1\AppData\Local\Temp\pip-install-wqi2aa4v\bitprim-native\

**Comment by ztlovemst11** [comment]
install bitprim-native  always having problems. Please reply as soon as possible

**Comment by ztlovemst11** [comment]
I think  https://github.com/bitprim/bitprim/issues/28  Is the root cause of this problem，but how to slove?

**Comment by fpelliccioni** [comment]
Hey, thanks for the issue report.
We are working to fix the pip package.
Thanks and sorry!

**Comment by fpelliccioni** [comment]
bitprim-insight is "independent" of "bitprim-node-exe" in some sense. But you should be able to build both.

Could you describe every detail of your platform?
CPU
Operating System
C++ Compiler 
conan --version
etcetera

We will reproduce it in a similar machine.
Thanks!

**Comment by ztlovemst11** [comment]
CPU : intel i5-2520M
Operating System : win 10
C++ Compiler : gcc 8.1
conan --version :1.6.1
